version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.jetson
    volumes:
      - ./:/workspace:cached
    working_dir: /workspace
    command: bash
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
