FROM nvcr.io/nvidia/l4t-base:r36.2.0

# install build tools
RUN apt-get update && apt-get install -y \
    build-essential \
    pkg-config \
    curl \
    git

# install rustup
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

WORKDIR /workspace
